### PR TITLE
updated distros and added others

### PR DESCRIPTION
**Pull request by jeremywakeman**

### CODE REVIEW

**Comment by jeremywakeman** [comment]
I updated several of the distros and added several others. No changes to code in this branch.

**Comment by gnarlin** [comment]
This is my first EVER pull request. Thank you so much for doing this!
Ok. I've read through the pull request and almost everything looks good but can you please remove the /old folder? I want the oslist structure to be consistent everywhere and I haven't tried to check if osget can read anything put in further subfolders. Besides, for rolling release distros there's no need to keep old versions of them around. I do intent to put every single version of Debian that has ever existed into oslist... eventually. That's the dream anyway.

**Comment by gnarlin** [comment]
Would it be easier if I just murged this request and then deleted the /old folder myself and pushed upstream again?
If you would prefer that let me know. I'm new at this.

**Comment by gnarlin** [comment]
Woot! I've merged it! I'm pumped! Thank you so very much. If you contribute anymore I'll more that too. Or if you have any suggestions etc.

**Pull request merged**
