### PR TITLE
Added 5 new distros

### PR DESCRIPTION
**Pull request by ShalmonAnandas**
Full changelog of added distros:
EndeavourOS 64bit
Kali linux full ISO 64bit & 32bit
Kali linux NetInstall 64bit & 32bit
Kali linux LiveUSB 64bit & 32bit
Zorin OS Core 64bit
Zorin OS Lite 64bit & 32bit
Void Linux Base 64bit & 32bit
Void Linux cinnamon 64bit & 32bit
Void linux enlightenment 64bit & 32bit
Void linux lxde 64bit & 32bit
Void linux lxqt 64bit & 32bit
Void linux mate 64bit & 32bit
Void linux xfce  64bit & 32bit
Garuda Linux Barebones Gnome 64bit
Garuda Linux Barebones KDE 64bit
Garuda Linux BSPWM 64bit
Garuda Linux Gnome 64bit
Garuda Linux i3WM 64bit
Garuda Linux Dr460nized 64bit
Garuda Linux Dr460nized Gaming Edition 64bit
Garuda Linux Dr460nized Black Arch Edition 64bit
Garuda Linux LXQT-Kwin 64bit
Garuda Linux Mate 64bit
Garuda Linux Qtile 64bit
Garuda Linux Sway 64bit
Garuda Linux Wayfire 64bit
Garuda Linux XFCE 64bit

### CODE REVIEW

**Comment by gnarlin** [comment]
I'll check this over after work and merge it tonight. Thank you so much :-D

**Comment by ShalmonAnandas** [comment]
Thats great! Loved the project!

**Review by gnarlin — CHANGES_REQUESTED** [review]
Can you please change the file names of the configuration files to reflect the filenames of the .iso files? Include everything in the name as the filename up to the dot (ie. garuda-bspwm-linux-zen-210809 and not just Garuda-BSPWM-amd64. It's the only way to keep every version separate. When the number of distros and versions start to number in the hundreds or the thousands this will become very important.

**Comment by ShalmonAnandas** [comment]
Yeah sure! That was a oversight on my behalf. I will make the changes as soon as I'm done with class tomorrow morning.

**Pull request closed without merging**
